#Preferences for outputs from tags used in automatic compat in recipes
tagPreferences = ["minecraft", "tconstruct", "tmechworks", "mekanism", "create", "immersiveengineering", "thermalfoundation", "thermalexpansion"]

