
[General]
	#Add SimpleOres items to chest loot?
	AddModLootToChests = false
	#Enable Simple Ores aesthetic blocks?
	EnableAestheticsBlocks = false

[Tools]
	#false disables recipes
	EnableCopperTools = true
	#false disables recipes
	EnableTinTools = true
	#false disables recipes
	EnableMythrilTools = true
	#false disables recipes
	EnableAdamantiumTools = true
	#false disables recipes
	EnableOnyxTools = false
	#false disables recipes
	EnableCopperBucket = true
	#false disables milking cows with copper bucets
	EnableCopperBucketMilking = false
	#liquids at temperature C or higher melt copper buckets
	#Range: -200 ~ 5000
	CopperBucketMeltTemperature = 1000
	#Copper is a good heat conductor. Liquids at this temp or higher set you on fire. Leave at 9999 to disable
	#Range: 300 ~ 9999
	CopperBucketSetYouOnFireTemperature = 9999
	#false disables recipes
	EnableModBows = false

[Armor]
	#false disables recipes
	EnableCopperArmor = true
	#false disables recipes
	EnableTinArmor = true
	#false disables recipes
	EnableMythrilArmor = true
	#false disables recipes
	EnableAdamantiumArmor = false
	#false disables recipes
	EnableOnyxArmor = true

